proxy/network: fix the tid builtin key error
Sometimes, previous tid generator could cause the exception below:

Traceback (most recent call last):
  File
"/home/borun/.local/lib/python3.5/site-packages/twisted/python/log.py",
line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File
"/home/borun/.local/lib/python3.5/site-packages/twisted/python/context.py",
line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File
"/home/borun/.local/lib/python3.5/site-packages/twisted/python/context.py",
line 85, in callWithContext
    return func(*args,**kw)
  File
"/home/borun/.local/lib/python3.5/site-packages/twisted/internet/asyncioreactor.py",
line 136, in _readOrWrite
    why = method()
--- <exception caught here> ---
  File
"/home/borun/.local/lib/python3.5/site-packages/twisted/internet/udp.py",
line 249, in doRead
    self.protocol.datagramReceived(data, addr)
  File "/home/borun/cpchain/cpchain/proxy/network.py", line 179, in
datagramReceived
    self.accept_response(tid, data)
  File "/home/borun/cpchain/cpchain/proxy/network.py", line 185, in
accept_response
    d, timeout = self.request[tid]
builtins.KeyError: 'Ç;,y\x1bá0®aCwôº\x14TJøÏ\x01F'