proxy/ssl-cert: support self-signed https ip-only hosts
Proxy used to disble the SSL certificate verification
by setting '_sslverify.platformTrust' to 'lambda: None',
which worked well for hostname(e.g. localhost), but raised
exception below for ip address. This patch is used to fix
this issue.

2018-05-21 16:32:53+0800 [HTTP11ClientProtocol
(TLSMemoryBIOProtocol),client] Error during info_callback
	Traceback (most recent call last):
	  File
"/home/borun/.local/lib/python3.5/site-packages/twisted/protocols/tls.py",
line 315, in dataReceived
	    self._checkHandshakeStatus()
	  File
"/home/borun/.local/lib/python3.5/site-packages/twisted/protocols/tls.py",
line 235, in _checkHandshakeStatus
	    self._tlsConnection.do_handshake()
	  File
"/home/borun/.local/lib/python3.5/site-packages/OpenSSL/SSL.py", line
1805, in do_handshake
	    result = _lib.SSL_do_handshake(self._ssl)
	  File
"/home/borun/.local/lib/python3.5/site-packages/OpenSSL/SSL.py", line
1226, in wrapper
	    callback(Connection._reverse_mapping[ssl], where,
return_code)
	--- <exception caught here> ---
	  File
"/home/borun/.local/lib/python3.5/site-packages/twisted/internet/_sslverify.py",
line 1103, in infoCallback
	    return wrapped(connection, where, ret)
	  File
"/home/borun/.local/lib/python3.5/site-packages/twisted/internet/_sslverify.py",
line 1202, in _identityVerifyingInfoCallback
	    verifyHostname(connection, self._hostnameASCII)
	  File
"/home/borun/.local/lib/python3.5/site-packages/service_identity/pyopenssl.py",
line 48, in verify_hostname
	    obligatory_ids=[DNS_ID(hostname)],
	  File
"/home/borun/.local/lib/python3.5/site-packages/service_identity/_common.py",
line 245, in __init__
	    raise ValueError("Invalid DNS-ID.")
	builtins.ValueError: Invalid DNS-ID.